# Generated by Django 5.0.6 on 2024-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('Нарассмотрении', 'Нарассмотрении'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], default='Нарассмотрении', max_length=255),
        ),
    ]
