# Generated by Django 5.0.6 on 2024-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('Новое', 'Новое'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], default='Новое', max_length=255),
        ),
    ]
