# Generated by Django 5.0.6 on 2024-05-22 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_statement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='update_at',
        ),
        migrations.AddField(
            model_name='statement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 10, 21, 28, 688903, tzinfo=datetime.timezone.utc), help_text='Выберите дату и время в диапазоне 8:00 - 21:00', verbose_name='Дата и время'),
        ),
    ]
