# Generated by Django 5.0.6 on 2024-05-22 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_statement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 10, 22, 22, 838506, tzinfo=datetime.timezone.utc), help_text='Выберите дату и время в диапазоне 8:00 - 21:00', verbose_name='Дата и время'),
        ),
    ]
